name: Run tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # À lancer en Python 3.8 et 3.9
        python-version: [3.8, 3.9, 3.11]

    steps:
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # Affiche la version de Python utilisée
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install de pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        # Installation des packages dont la liste est comprise dans requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        # Lancement du test
      - name: Run tests
        run: pytest tests.py